// Package cobanovic is the seeding module for the real Grafika Čobanović data
// set migrated from the shop's legacy FoxPro/dBASE system.
//
// This package is the connector only — it carries no data. The actual data lives
// in the git-ignored ./data folder as data/seed.json, generated by ./import.py
// from the legacy export. Regenerate it before seeding (see ./README.md).
package cobanovic

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/LosBobes/iris/iris-api/internal/domain"
	"github.com/LosBobes/iris/iris-api/internal/store"
)

// DefaultDataDir is the in-repo location of the (git-ignored) seed data, relative
// to the iris-api module root where irisctl runs.
const DefaultDataDir = "internal/seed/cobanovic/data"

// seedFileName is the single JSON file holding the imported data set.
const seedFileName = "seed.json"

// seedData is the shape of data/seed.json produced by import.py.
type seedData struct {
	Customers    []domain.Customer    `json:"customers"`
	Locations    []domain.Location    `json:"locations"`
	CatalogItems []domain.CatalogItem `json:"catalogItems"`
	WorkOrders   []workOrder          `json:"workOrders"`
}

// workOrder is the minimal work-order shape stored in the seed file. It is
// expanded into a full domain.WorkOrder so the seed exercises the same
// persistence path as live work orders.
type workOrder struct {
	ID             string                 `json:"id"`
	OrderNumber    string                 `json:"orderNumber"`
	CustomerID     *string                `json:"customerId"`
	LocationID     *string                `json:"locationId"`
	ClientName     string                 `json:"clientName"`
	ContactPerson  *string                `json:"contactPerson"`
	JobDescription string                 `json:"jobDescription"`
	IssuedBy       string                 `json:"issuedBy"`
	IssueDate      string                 `json:"issueDate"`
	DueDate        *string                `json:"dueDate"`
	Status         domain.WorkOrderStatus `json:"status"`
	Price          *float64               `json:"price"`
	Note           *string                `json:"note"`
	InvoiceDraft   domain.InvoiceDraft    `json:"invoiceDraft"`
}

// Seed loads the Čobanović data set from <dir>/seed.json into the SQLite store:
// ~2657 client firms, ~3575 catalog items, and a few demo work orders. It also
// creates the login accounts the shop signs in with. Upserts make it re-runnable.
func Seed(ctx context.Context, sqliteStore *store.SQLiteStore, dir string) error {
	// All Čobanović data belongs to the production tenant, which the tenant
	// isolation migration already created. Scope every write below to it.
	ctx = store.ContextWithTenant(ctx, store.ProductionTenantID)

	path := filepath.Join(dir, seedFileName)

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf(
				"seed data %q not found — generate it first with internal/seed/cobanovic/import.py",
				path,
			)
		}
		return err
	}
	var seed seedData
	if err := json.Unmarshal(data, &seed); err != nil {
		return fmt.Errorf("decode %s: %w", path, err)
	}

	// Login accounts: admin (manages catalog/customers) + a regular operator.
	if err := sqliteStore.CreateUser(ctx, "user-admin", "admin", "admin123", domain.RoleAdmin, true); err != nil {
		return fmt.Errorf("seed admin user: %w", err)
	}
	if err := sqliteStore.CreateUser(ctx, "user-operater", "operater", "operater123", domain.RoleUser, true); err != nil {
		return fmt.Errorf("seed operator user: %w", err)
	}

	for _, customer := range seed.Customers {
		if _, err := sqliteStore.UpsertCustomer(ctx, customer); err != nil {
			return fmt.Errorf("seed customer %s: %w", customer.ID, err)
		}
	}
	// Locations reference their parent customer, so they must be upserted after
	// the customers above (UpsertLocation rejects an unknown/other-tenant client).
	for _, location := range seed.Locations {
		if _, err := sqliteStore.UpsertLocation(ctx, location); err != nil {
			return fmt.Errorf("seed location %s: %w", location.ID, err)
		}
	}
	for _, item := range seed.CatalogItems {
		if _, err := sqliteStore.UpsertCatalogItem(ctx, item, ""); err != nil {
			return fmt.Errorf("seed catalog item %s: %w", item.ID, err)
		}
	}
	for _, raw := range seed.WorkOrders {
		if err := sqliteStore.PutWorkOrder(ctx, expandWorkOrder(raw)); err != nil {
			return fmt.Errorf("seed work order %s: %w", raw.ID, err)
		}
	}

	return nil
}

func expandWorkOrder(raw workOrder) domain.WorkOrder {
	now := time.Now().UTC().Format(time.RFC3339)
	status := raw.Status
	if status == "" {
		status = domain.WorkOrderStatusNew
	}
	invoice := raw.InvoiceDraft
	if invoice.LineItems == nil {
		invoice.LineItems = []domain.InvoiceLineItem{}
	}
	return domain.WorkOrder{
		ID:             raw.ID,
		OrderNumber:    raw.OrderNumber,
		CustomerID:     raw.CustomerID,
		LocationID:     raw.LocationID,
		ClientName:     raw.ClientName,
		ContactPerson:  raw.ContactPerson,
		JobDescription: raw.JobDescription,
		Shipping:       domain.Shipping{},
		IssuedBy:       raw.IssuedBy,
		Assignment:     domain.Assignment{Priority: domain.WorkOrderPriorityNormal},
		IssueDate:      raw.IssueDate,
		DueDate:        raw.DueDate,
		Status:         status,
		IsCompleted:    status == domain.WorkOrderStatusCompleted || status == domain.WorkOrderStatusInvoiced,
		Price:          raw.Price,
		Note:           raw.Note,
		CreatedAt:      now,
		UpdatedAt:      now,
		StatusHistory:  []domain.WorkOrderStatusHistory{{Status: status, ChangedAt: now, ChangedBy: raw.IssuedBy}},
		InternalNotes:  []domain.WorkOrderNote{},
		CustomerNotes:  []domain.WorkOrderNote{},
		Events:         []domain.WorkOrderEvent{{ID: "event-created", Kind: "created", Label: "Nalog uvezen", Actor: raw.IssuedBy, CreatedAt: now}},
		Attachments:    []domain.Attachment{},
		MaterialUsage:  []domain.MaterialUsage{},
		TimeEntries:    []domain.TimeEntry{},
		InvoiceDraft:   invoice,
		Communication:  domain.CustomerCommunication{PublicToken: "wo-" + raw.ID},
	}
}
